# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

#An environment variables for the home and work directories
export WORK="/user/work/${USER}"

#Default project code
export HPC_PROJECT_CODE="COSC020762"

#Default queue
export DEFAULT_QUEUE="cnu"

#Scripts for submitting jobs in the infrastructure repo (assuming you've cloned to this location)
export PATH="$PATH:${HOME}/infrastructure/blue_pebble/bin"

#A nicer prompt
export PS1="\w $ "

#Alias for vim
alias vim=vi

#Alias for measuring the size of a directory without following symlinks
alias dirsize='du -sPh'

#All caches, including Pip, HF etc. in the work directory
export XDG_CACHE_HOME="${WORK}/.cache"

#Force Pip to use virtualenvs for all installs
export PIP_REQUIRE_VIRTUALENV=1

#Reasonably recent version of Python
module add languages/python/3.12.3

