#!/bin/env bash

set -euo pipefail

port=$(shuf -i 6000-9999 -n 1)
echo "Using port $port"
echo "Once the job has started on the cluster, navigate to http://localhost:${port}"
echo "If the connection closes prematurely then run 'ssh -N -L ${port}:localhost:${port} bp' to re-open the tunnel."

ssh -t -L ${port}:localhost:${port} bp "lsub $@ --port ${port} --cmd 'jupyter notebook --no-browser --port ${port}'"

echo "Connection closed. Please make sure the job is cancelled."
